version: '3'

services:
  db:
    image: mysql:8
    command: --innodb-use-native-aio=0
    container_name: devbook-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devbook
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - devbook-network

networks:
  devbook-network:
    driver: bridge